coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0.5%

comment:
  require_changes: yes

ignore:
  - "xrspatial/__init__.py"
  - "xrspatial/__main__.py"
  - "xrspatial/experimental/*"
  - "xrspatial/gpu_rtx/*"
  - "xrspatial/tests/*"
  - "./setup.py"