coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0.5%

comment:
  require_changes: yes

ignore:
  - "xrspatial/tests/*"
  - "xrspatial/experimental/*"
  - "xrspatial/gpu_rtx/*"
